# Generated by Django 4.0.2 on 2023-08-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextacloudapp', '0002_staff_remove_store_manager_id_alter_store_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentAndItems',
            new_name='Items',
        ),
    ]
