# Generated by Django 4.0.2 on 2023-08-26 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextacloudapp', '0003_rename_equipmentanditems_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='manager',
        ),
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nextacloudapp.store'),
        ),
    ]
