# Generated by Django 4.0.2 on 2023-08-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextacloudapp', '0005_rename_brand_items_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='condition',
            new_name='store',
        ),
    ]
