# Generated by Django 4.0.2 on 2023-08-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextacloudapp', '0006_rename_condition_items_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
